apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dragonfly-dfclient.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dragonfly-dfclient.name" . }}
    helm.sh/chart: {{ include "dragonfly-dfclient.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $val := .Values.configFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
